#!/bin/sh

# Set these paths appropriately

BIN="/home/mlopezmalet/tree-tagger/bin"
CMD="/home/mlopezmalet/tree-tagger/cmd"
LIB="/home/mlopezmalet/tree-tagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations
PARFILE=${LIB}/french.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
